server:
  port: 18080

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: io.seata.samples.sca.provider.dubbo
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: ""

spring:
  application:
    name: sca-provider
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.186.128:3306/yuhb-test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456



  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: sca-provider-seata-tx-service-group

mybatis:
  mapper-locations: classpath:mapper/*.xml
