server:
  port: 8080
spring:
  application:
    name: tm
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: file
  registry:
    type: file
logging:
  level:
    root: info
  file:
    path: ${user.home}/logs/${spring.application.name}
dubbo:
  application:
    id: dubbo-tm
    name: dubbo-tm
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
  registry:
    id: dubbo-seata-examples-registry
    address: multicast://224.0.0.1:1234?unicast=false