server:
  port: 8888
spring:
  application:
    name: business-starter-samples
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_server1?useAffectedRows=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

seata:
  enabled: true #开启配置
  application-id: business-starter-samples  #客户端注册ID
  tx-service-group: default # 事务分组
  client:
    rm-async-commit-buffer-limit: 1000
    rm-report-retry-count: 5
    rm-table-meta-check-enable: false
    rm-report-success-enable: true
    rm:
      lock:
        lock-retry-interval: 10
        lock-retry-times: 30
        lock-retry-policy-branch-rollback-on-conflict: true
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 5
    support:
      spring:
        datasource-autoproxy: true # 数据源自动注入
    undo:
      undo-data-validation: true
      undo-log-serialization: jackson
      undo-log-table: undo_log     # 回滚事务表
    client:
      log:
        exceptionRate: 100
  service:
    vgroup-mapping: default
    grouplist: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true       # client和server通信心跳检测开关
    serialization: seata  # client和server通信编解码方式
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: file
    file:
      name: file.conf
    consul:
      server-addr: 127.0.0.1:8500
    apollo:
      apollo-meta: http://192.168.1.204:8801
      app-id: eureka
    etcd3:
      server-addr: http://localhost:2379
    nacos:
      namespace:
      serverAddr: localhost
    zk:
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
  registry:
    type: file     # yml 与 conf中配置同级，默认执行顺序 file.conf -> application.yml
    file:
      name: file.conf
    consul:
      cluster: default
      server-addr: 127.0.0.1:8500
    etcd3:
      cluster: default
      serverAddr: http://localhost:2379
    eureka:
      application: seata-client
      weight: 1
      service-url: http://127.0.0.1:8761/eureka
    nacos:
      cluster: default
      server-addr: localhost
      namespace:
    redis:
      server-addr: localhost:6379
      db: 0
    sofa:
      server-addr: 127.0.0.1:9603
      application: default
      region: DEFAULT_ZONE
      datacenter: DefaultDataCenter
      cluster: default
      group: SEATA_GROUP
      addressWaitTime: 3000
    zk:
      cluster: default
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
