server:
  port: 8082
spring:
  application:
    name: xa-rm
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seata-samples?autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: seata
      password: seata
      initialSize: 50
      minIdle: 50
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=500
      useGlobalDataSourceStat: true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: io.seata.samples.bean
  configuration:
    cacheEnabled: true
    lazyLoadingEnabled: false
    aggressiveLazyLoading: false
    multipleResultSetsEnabled: true
    useColumnLabel: true
    useGeneratedKeys: true
    autoMappingBehavior: FULL
    defaultExecutorType: SIMPLE
    defaultStatementTimeout: 25000
    mapUnderscoreToCamelCase: true
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
mapper:
  mappers: io.seata.samples.utils.MyMapper
  not-empty: false
  identity: MYSQL
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: file
  registry:
    type: file
  data-source-proxy-mode: XA
  enable-auto-data-source-proxy: true
logging:
  level:
    root: info
    io.seata.samples.service: TRACE
  file:
    path: ${user.home}/logs/${spring.application.name}
