server:
  port: 8081
spring:
  application:
    name: at-rm
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.183:3306/seata_test_rm?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
      username: truthtest
      password: truthtest11
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=500
      useGlobalDataSourceStat: true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: io.seata.samples.bean
  configuration:
    cacheEnabled: true
    lazyLoadingEnabled: false
    aggressiveLazyLoading: false
    multipleResultSetsEnabled: true
    useColumnLabel: true
    useGeneratedKeys: true
    autoMappingBehavior: FULL
    defaultExecutorType: SIMPLE
    defaultStatementTimeout: 25000
    mapUnderscoreToCamelCase: true
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
mapper:
  mappers: io.seata.samples.utils.MyMapper
  not-empty: false
  identity: MYSQL
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: file
  registry:
    type: file
  data-source-proxy-mode: AT
  enable-auto-data-source-proxy: true
logging:
  level:
    root: info
    io.seata.samples.mapper: TRACE
  file:
    path: ${user.home}/logs/${spring.application.name}
