eureka:
    instance:
        hostname: 192.168.168.168
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.seata.sample.entity
server:
    port: 8181
spring:
    application:
        name: account-server
    cloud:
        alibaba:
            seata:
                tx-service-group: default
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://116.62.xx.xx/seata-account
        password: xxxx
        username: root
logging:
  level:
    root: info
# -----------seata--------------
# -----------seata--------------
